MDMS/Web/MDMS.Web/Areas/Administration/Controllers/VehicleController.cs
using System;
using System.Threading.Tasks;
using MDMS.GlobalConstants;
using MDMS.Services;
using MDMS.Services.Mapping;
using MDMS.Services.Models;
using MDMS.Web.BindingModels.Vehicle.Create;
using MDMS.Web.ViewModels.Vehicle.Edit;
using Microsoft.AspNetCore.Mvc;

namespace MDMS.Web.Areas.Administration.Controllers
{
    public class VehicleController : AdminController
    {
        private readonly IVehicleService _vehicleService;
        private readonly ICloudinaryService _cloudinaryService;

        public VehicleController(IVehicleService vehicleService, ICloudinaryService cloudinaryService)
        {
            _vehicleService = vehicleService;
            _cloudinaryService = cloudinaryService;
        }

        [HttpGet]
        [Route("/Administration/Vehicle/Provider/Create")]
        public async Task<IActionResult> CreateProvider() => await Task.Run(() => this.View("Provider/Create"));


        [HttpPost]
        [Route("/Administration/Vehicle/Provider/Create")]
        public async Task<IActionResult> CreateProvider(VehicleProviderCreateBindingModel vehicleProviderBindingModel)
        {
            if (ModelState.IsValid)
            {
                VehicleProviderServiceModel vehicleProviderServiceModel =
                    AutoMapper.Mapper.Map<VehicleProviderServiceModel>(vehicleProviderBindingModel);

                var result = await _vehicleService.CreateVehicleProvider(vehicleProviderServiceModel);

                if (result) return this.Redirect("/");

                this.ViewData["error"] = ControllerConstants.VehicleProviderCreateErrorMessage;
                return this.View("Provider/Create", vehicleProviderBindingModel);
            }
            this.ViewData["error"] = ControllerConstants.InputErrorMessage;
            return this.View("Provider/Create", vehicleProviderBindingModel);
        }

        [HttpGet]
        [Route("/Administration/Vehicle/Type/Create")]
        public async Task<IActionResult> CreateType() => await Task.Run(() => this.View("Type/Create"));

        [HttpPost]
        [Route("/Administration/Vehicle/Type/Create")]
        public async Task<IActionResult> CreateType(VehicleTypeCreateBindingModel vehicleTypeCreateBindingModel)
        {
            if (ModelState.IsValid)
            {
                VehicleTypeServiceModel vehicleTypeServiceModel =
                    AutoMapper.Mapper.Map<VehicleTypeServiceModel>(vehicleTypeCreateBindingModel);

                var result = await _vehicleService.CreateVehicleType(vehicleTypeServiceModel);

                if (result) return this.Redirect("/");

                this.ViewData["error"] = ControllerConstants.VehicleTypeCreateErrorMessage;
                return this.View("Type/Create", vehicleTypeCreateBindingModel);
            }
            this.ViewData["error"] = ControllerConstants.InputErrorMessage;
            return this.View("Type/Create", vehicleTypeCreateBindingModel);
        }

        [HttpGet(Name = "Create")]
        public async Task<IActionResult> Create() => await Task.Run(this.View);


        [HttpPost(Name = "Create")]
        public async Task<IActionResult> Create(VehicleCreateBindingModel vehicleCreateBindingModel)
        {
            if (ModelState.IsValid)
            {
                string pictureUrl = await _cloudinaryService.UploadPictureAsync(vehicleCreateBindingModel.Picture,
                    vehicleCreateBindingModel.VSN);

                VehicleServiceModel vehicleServiceModel =
                    AutoMapper.Mapper.Map<VehicleServiceModel>(vehicleCreateBindingModel);
                vehicleServiceModel.Picture = pictureUrl;

                var result = await _vehicleService.Create(vehicleServiceModel);

                if (result) return this.RedirectToAction("All");

                this.ViewData["error"] = ControllerConstants.VehicleCreateErrorMessage;
                return this.View(vehicleCreateBindingModel);
            }
            this.ViewData["error"] = ControllerConstants.InputErrorMessage;
            return this.View(vehicleCreateBindingModel);
        }

        [HttpGet(Name = "Edit")]
        public async Task<IActionResult> Edit(string name)
        {
            return await Task.Run((() =>
                    this.View(_vehicleService.GetVehicleByName(name).Result.To<VehicleEditViewModel>())));
        }


        [HttpPost(Name = "Edit")]
        public async Task<IActionResult> Edit(VehicleEditBindingModel vehicleEditBindingModel)
        {
            if (ModelState.IsValid)
            {
                var result = await _vehicleService.Edit(vehicleEditBindingModel.To<VehicleServiceModel>());

                if (result)
                {
                    this.ViewData["error"] = ControllerConstants.VehicleEditErrorMessage;
                    return this.Redirect($"/Vehicle/Details?name={vehicleEditBindingModel.Name}");
                }

                return this.RedirectToAction("Edit", vehicleEditBindingModel);
            }
            this.ViewData["error"] = ControllerConstants.InputErrorMessage;
            return this.RedirectToAction("Edit", vehicleEditBindingModel);
        }

        public async Task<IActionResult> Delete(string id)
        {
            await _vehicleService.DeleteVehicle(id);
            return RedirectToAction("All");
        }
    }
}

MDMS/Web/MDMS.Web/Controllers/VehicleController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Mdms.Data.Models;
using MDMS.Services;
using MDMS.Services.Mapping;
using MDMS.Web.ViewModels.Vehicle.All;
using MDMS.Web.ViewModels.Vehicle.Details;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace MDMS.Web.Controllers
{
    public class VehicleController : UserController
    {
        private readonly IVehicleService _vehicleService;
        private readonly UserManager<MdmsUser> _userManager;

        public VehicleController(IVehicleService vehicleService, UserManager<MdmsUser> userManager)
        {
            _vehicleService = vehicleService;
            _userManager = userManager;
        }

        [HttpGet(Name = "All")]
        public async Task<IActionResult> All() =>
            await Task.Run(() => this.View(_vehicleService.GetAllVehicles().To<VehicleAllViewModel>().ToList()));


        [HttpGet(Name = "Details")]
        public async Task<IActionResult> Details(string name)
        {

            var user = await _userManager.GetUserAsync(User);
            var vehicleDetails = _vehicleService.GetVehicleByName(name).Result.To<VehicleDetailsViewModel>();
            vehicleDetails.MDMSUserServiceModelIsRepairing = user.IsRepairing;
            return this.View(vehicleDetails);
        }
    }
}

MDMS/Web/MDMS.Web/ViewComponents/VehicleProviderViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MDMS.Services;
using MDMS.Web.ViewModels;
using MDMS.Web.ViewModels.ViewComponents;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MDMS.Web.ViewComponents
{
    public class VehicleProviderViewComponent : ViewComponent
    {
        private readonly IVehicleService _vehicleService;

        public VehicleProviderViewComponent(IVehicleService vehicleService)
        {
            _vehicleService = vehicleService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var vehicleCreateVehicleProviderViewModels = await _vehicleService.GetAllVehicleProviders()
                .OrderBy(vt => vt.Name)
                .Select(vt => new VehicleProviderViewComponentViewModel() { Name = vt.Name })
                .ToListAsync();

            return View(vehicleCreateVehicleProviderViewModels);
        }
    }
}

MDMS/Web/MDMS.Web/ViewComponents/VehicleTypeViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MDMS.Services;
using MDMS.Web.ViewModels.ViewComponents;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MDMS.Web.ViewComponents
{
    public class VehicleTypeViewComponent : ViewComponent
    {
        private readonly IVehicleService _vehicleService;

        public VehicleTypeViewComponent(IVehicleService vehicleService)
        {
            _vehicleService = vehicleService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var vehicleTypeViewComponentViewModels = await _vehicleService.GetAllVehicleTypes()
                .OrderBy(vt => vt.Name)
                .Select(vt => new VehicleTypeViewComponentViewModel(){Name = vt.Name})
                .ToListAsync();

            return View(vehicleTypeViewComponentViewModels);
        }

    }
}

MDMS/Web/MDMS.Web/Areas/Administration/Views/Vehicle/Create.cshtml
@model MDMS.Web.BindingModels.Vehicle.Create.VehicleCreateBindingModel
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="bg-primary text-white font-weight-bold text-center p-2 w-60 mx-auto rounded">Create Vehicle</h1>
<form method="post" class="form border-primary-4 rounded p-3 w-60 mx-auto mt-2 bg-white" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    @if (this.ViewData["error"] != null)
    {
        <ul>
            <li  class="text-danger">@this.ViewData["error"]</li>
        </ul>
    }
    <div id="make-and-model-holder" class="d-flex justify-content-between">
        <div class="form-group mx-auto w-45">
            <div class="d-flex justify-content-center">
                <label asp-for="Make" class="text-primary h5">Make</label>
            </div>
            <input type="text"
                   class="form-control text-primary text-center"
                   id="make"
                   placeholder="Make..."
                   asp-for="Make">
            <span asp-validation-for="Make" class="text-danger"></span>
        </div>
        <div class="form-group mx-auto w-45">
            <div class="d-flex justify-content-center">
                <label asp-for="Model" class="text-primary h5">Model</label>
            </div>
            <input type="text"
                   class="form-control text-primary text-center"
                   id="model"
                   placeholder="Model..."
                   asp-for="Model">
            <span asp-validation-for="Model" class="text-danger"></span>
        </div>
    </div>
    <div id="vsn-and-picture-holder" class="d-flex justify-content-between">
        <div class="form-group mx-auto w-45">
            <div class="d-flex justify-content-center">
                <label asp-for="VSN" class="text-primary h5">VSN</label>
            </div>
            <input type="text"
                   class="form-control text-primary text-center"
                   id="vsn"
                   placeholder="Model..."
                   asp-for="VSN">
            <span asp-validation-for="VSN" class="text-danger"></span>
        </div>
        <div class="form-group mx-auto w-45">
            <div class="d-flex justify-content-center">
                <label asp-for="Picture" class="text-primary h5">Picture</label>
            </div>
            <input type="file"
                   class="form-control text-primary text-center"
                   id="picture"
                   placeholder="Picture..."
                   asp-for="Picture">
            <span asp-validation-for="Picture" class="text-danger"></span>
        </div>
    </div>
    <div id="ManufacturedOn-and-AcquiredOn-holder" class="d-flex justify-content-between">
        <div class="form-group mx-auto w-45">
            <div class="d-flex justify-content-center">
                <label asp-for="ManufacturedOn" class="text-primary h5">Manufactured On</label>
            </div>
            <input type="text"
                   class="form-control text-primary text-center"
                   id="manufacturedOn"
                   placeholder="Manufactured On..."
                   asp-for="ManufacturedOn">
            <span asp-validation-for="ManufacturedOn" class="text-danger"></span>
        </div>
        <div class="form-group mx-auto w-45">
            <div class="d-flex justify-content-center">
                <label asp-for="AcquiredOn" class="text-primary h5">Acquired On</label>
            </div>
            <input type="text"
                   class="form-control text-primary text-center"
                   id="acquiredOn"
                   placeholder="Manufactured On..."
                   asp-for="AcquiredOn">
            <span asp-validation-for="AcquiredOn" class="text-danger"></span>
        </div>
    </div>
    <div id="date-and-Depreciation-holder" class="d-flex justify-content-between">
        <div class="form-group mx-auto w-45">
            <div class="d-flex justify-content-center">
                <label asp-for="Price" class="text-primary h5">Price</label>
            </div>
            <input type="number"
                   step="0.01"
                   class="form-control text-primary text-center"
                   id="price"
                   placeholder="Price..."
                   asp-for="Price">
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
        <div class="form-group mx-auto w-45">
            <div class="d-flex justify-content-center">
                <label asp-for="Depreciation" class="text-primary h5">Depreciation</label>
            </div>
            <input type="number"
                   step="0.01"
                   class="form-control text-primary text-center"
                   id="depreciation"
                   placeholder="Depreciation..."
                   asp-for="Depreciation">
            <span asp-validation-for="Depreciation" class="text-danger"></span>
        </div>
    </div>
    <div id="mileage-and-regNumber-holder" class="d-flex justify-content-between">
        <div class="form-group mx-auto w-45">
            <div class="d-flex justify-content-center">
                <label asp-for="Mileage" class="text-primary h5">Mileage</label>
            </div>
            <input type="number"
                   step="1"
                   class="form-control text-primary text-center"
                   id="mileage"
                   placeholder="Mileage..."
                   asp-for="Mileage">
            <span asp-validation-for="Mileage" class="text-danger"></span>
        </div>
        <div class="form-group mx-auto w-45">
            <div class="d-flex justify-content-center">
                <label asp-for="RegistrationNumber" class="text-primary h5">RegistrationNumber</label>
            </div>
            <input type="text"
                   class="form-control text-primary text-center"
                   id="registrationNumber"
                   placeholder="RegistrationNumber..."
                   asp-for="RegistrationNumber">
            <span asp-validation-for="RegistrationNumber" class="text-danger"></span>
        </div>
    </div>
    <hr class="hr-2 bg-primary mt-4">
    <div class="form-group mx-auto w-45">
        <div class="d-flex justify-content-center">
            <label asp-for="VehicleType" class="text-primary h5">Vehicle Type</label>
        </div>
        <select class="form-control text-primary" id="vehicleType" asp-for="VehicleType">
            <option selected disabled>--- Select Vehicle Type ---</option>
            <vc:vehicle-type></vc:vehicle-type>
        </select>
        <span asp-validation-for="VehicleType" class="text-danger"></span>
    </div>
    <div class="form-group mx-auto w-45">
        <div class="d-flex justify-content-center">
            <label asp-for="VehicleProvider" class="text-primary h5">Vehicle Provider</label>
        </div>
        <select class="form-control text-primary" id="vehicleProvider" asp-for="VehicleProvider">
            <option selected disabled>--- Select Vehicle Provider ---</option>
            <vc:vehicle-provider></vc:vehicle-provider>
        </select>
        <span asp-validation-for="VehicleProvider" class="text-danger"></span>
    </div>
    <hr class="hr-2 bg-primary mt-4">
    <div class="d-flex justify-content-center mt-3">
        <button class="btn btn-primary font-weight-bold">Create Vehicle</button>
    </div>
</form>


<script>
    window.onload = () => {
        $('#manufacturedOn').datetimepicker({
            format: 'm.d.Y H:i',
            lang: 'en'
        });
        $('#acquiredOn').datetimepicker({
            format: 'm.d.Y H:i',
            lang: 'en'
        });
    };
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MDMS/Web/MDMS.Web/Areas/Administration/Views/Vehicle/Edit.cshtml
@model MDMS.Web.ViewModels.Vehicle.Edit.VehicleEditViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="bg-primary text-white font-weight-bold text-center p-2 w-60 mx-auto rounded">Edit Vehicle - @Model.VSN</h1>
<form method="post" action="/Administration/Vehicle/Edit" class="form border-primary-4 rounded p-3 w-60 mx-auto mt-2 bg-white" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    @if (this.ViewData["error"] != null)
    {
        <ul>
            <li class="text-danger">@this.ViewData["error"]</li>
        </ul>
    }
    <div id="make-and-model-holder" class="d-flex justify-content-between">
        <div class="form-group mx-auto w-45">
            <div class="d-flex justify-content-center">
                <label asp-for="Make" class="text-primary h5">Make</label>
            </div>
            <input type="text"
                   class="form-control text-primary text-center"
                   id="make"
                   placeholder="Make..."
                   asp-for="Make">
            <span asp-validation-for="Make" class="text-danger"></span>
        </div>
        <div class="form-group mx-auto w-45">
            <div class="d-flex justify-content-center">
                <label asp-for="Model" class="text-primary h5">Model</label>
            </div>
            <input type="text"
                   class="form-control text-primary text-center"
                   id="model"
                   placeholder="Model..."
                   asp-for="Model">
            <span asp-validation-for="Model" class="text-danger"></span>
        </div>
    </div>
    <div id="ManufacturedOn-and-AcquiredOn-holder" class="d-flex justify-content-between">
        <div class="form-group mx-auto w-45">
            <div class="d-flex justify-content-center">
                <label asp-for="ManufacturedOn" class="text-primary h5">Manufactured On</label>
            </div>
            <input type="text"
                   class="form-control text-primary text-center"
                   id="manufacturedOn"
                   placeholder="Manufactured On..."
                   asp-for="ManufacturedOn">
            <span asp-validation-for="ManufacturedOn" class="text-danger"></span>
        </div>
        <div class="form-group mx-auto w-45">
            <div class="d-flex justify-content-center">
                <label asp-for="AcquiredOn" class="text-primary h5">Acquired On</label>
            </div>
            <input type="text"
                   class="form-control text-primary text-center"
                   id="acquiredOn"
                   placeholder="Manufactured On..."
                   asp-for="AcquiredOn">
            <span asp-validation-for="AcquiredOn" class="text-danger"></span>
        </div>
    </div>
    <div id="date-and-Depreciation-holder" class="d-flex justify-content-between">
        <div class="form-group mx-auto w-45">
            <div class="d-flex justify-content-center">
                <label asp-for="Price" class="text-primary h5">Price</label>
            </div>
            <input type="number"
                   step="0.01"
                   class="form-control text-primary text-center"
                   id="price"
                   placeholder="Price..."
                   asp-for="Price">
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
        <div class="form-group mx-auto w-45">
            <div class="d-flex justify-content-center">
                <label asp-for="Depreciation" class="text-primary h5">Depreciation</label>
            </div>
            <input type="number"
                   step="0.01"
                   class="form-control text-primary text-center"
                   id="depreciation"
                   placeholder="Depreciation..."
                   asp-for="Depreciation">
            <span asp-validation-for="Depreciation" class="text-danger"></span>
        </div>
    </div>
    <div id="mileage-and-regNumber-holder" class="d-flex justify-content-between">
        <div class="form-group mx-auto w-45">
            <div class="d-flex justify-content-center">
                <label asp-for="Mileage" class="text-primary h5">Mileage</label>
            </div>
            <input type="number"
                   step="0.01"
                   class="form-control text-primary text-center"
                   id="mileage"
                   placeholder="Mileage..."
                   asp-for="Mileage">
            <span asp-validation-for="Mileage" class="text-danger"></span>
        </div>
        <div class="form-group mx-auto w-45">
            <div class="d-flex justify-content-center">
                <label asp-for="RegistrationNumber" class="text-primary h5">RegistrationNumber</label>
            </div>
            <input type="text"
                   class="form-control text-primary text-center"
                   id="registrationNumber"
                   placeholder="RegistrationNumber..."
                   asp-for="RegistrationNumber">
            <span asp-validation-for="RegistrationNumber" class="text-danger"></span>
        </div>
    </div>
    <hr class="hr-2 bg-primary mt-4">
    <div class="form-group mx-auto w-45">
        <div class="d-flex justify-content-center">
            <label asp-for="VehicleType" class="text-primary h5">Vehicle Type</label>
        </div>
        <select class="form-control text-primary" id="vehicleType" asp-for="VehicleType">
            <option selected>@Model.VehicleType</option>
            <vc:vehicle-type></vc:vehicle-type>
        </select>
        <span asp-validation-for="VehicleType" class="text-danger"></span>
    </div>
    <div class="form-group mx-auto w-45">
        <div class="d-flex justify-content-center">
            <label asp-for="VehicleProvider" class="text-primary h5">Vehicle Provider</label>
        </div>
        <select class="form-control text-primary" id="vehicleProvider" asp-for="VehicleProvider">
            <option selected>@Model.VehicleProvider</option>
            <vc:vehicle-provider></vc:vehicle-provider>
        </select>
        <span asp-validation-for="VehicleProvider" class="text-danger"></span>
    </div>
    <hr class="hr-2 bg-primary mt-4">
    <div class="d-flex justify-content-center mt-3">
        <button class="btn btn-primary font-weight-bold">Edit Vehicle</button>
    </div>
    <input type="hidden" value="@Model.Id" name="Id" id="id" />
    <input type="hidden" value="@Model.Name" name="Name" id="name" />
    <input type="hidden" value="@Model.VSN" name="VSN" id="vsn" />
    <input type="hidden" value="@Model.Picture" name="Picture" id="picture" />
</form>


<script>
    window.onload = () => {
        $('#manufacturedOn').datetimepicker({
            format: 'm.d.Y H:i',
            lang: 'en'
        });
        $('#acquiredOn').datetimepicker({
            format: 'm.d.Y H:i',
            lang: 'en'
        });
    };
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}