MDMS/Web/MDMS.Web/Areas/Administration/Controllers/PartController.cs
using System;
using System.Threading.Tasks;
using MDMS.GlobalConstants;
using MDMS.Services;
using MDMS.Services.Mapping;
using MDMS.Services.Models;
using MDMS.Web.BindingModels.Part.Add;
using MDMS.Web.BindingModels.Part.Create;
using MDMS.Web.BindingModels.Part.Edit;
using MDMS.Web.ViewModels.Part.Edit;
using Microsoft.AspNetCore.Mvc;

namespace MDMS.Web.Areas.Administration.Controllers
{
    public class PartController : AdminController
    {
        private readonly IPartService _partService;

        public PartController(IPartService partService)
        {
            _partService = partService;
        }

        [HttpGet]
        [Route("/Administration/Part/Provider/Create")]
        public async Task<IActionResult> CreateProvider() => await Task.Run(() => this.View("Provider/Create"));


        [HttpPost]
        [Route("/Administration/Part/Provider/Create")]
        public async Task<IActionResult> CreateProvider(PartProviderBindingModel partProviderBindingModel)
        {
            if (ModelState.IsValid)
            {
                PartsProviderServiceModel vehicleProviderServiceModel = AutoMapper.Mapper.Map<PartsProviderServiceModel>(partProviderBindingModel);
                var result = await _partService.CreatePartProvider(vehicleProviderServiceModel);

                if (result) return this.Redirect("/");

                this.ViewData["error"] = ControllerConstants.PartProviderErrorMessage;
                return this.View("Provider/Create", partProviderBindingModel);
            }
            this.ViewData["error"] = ControllerConstants.InputErrorMessage;
            return this.View("Provider/Create", partProviderBindingModel);
        }


        [HttpGet(Name = "Create")]
        public async Task<IActionResult> Create()
        {
            return await Task.Run(this.View);
        }

        [HttpPost(Name = "Create")]
        public async Task<IActionResult> Create(PartCreateBindingModel partCreateBindingModel)
        {
            if (ModelState.IsValid)
            {
                PartServiceModel partServiceModel = AutoMapper.Mapper.Map<PartServiceModel>(partCreateBindingModel);
                var result = await _partService.Create(partServiceModel);

                if (result) return this.RedirectToAction("All");

                this.ViewData["error"] = ControllerConstants.PartErrorMessage;
                return this.View(partCreateBindingModel);
            }
            this.ViewData["error"] = ControllerConstants.InputErrorMessage;
            return this.View(partCreateBindingModel);
        }

        [HttpPost(Name = "AddStock")]
        public async Task<IActionResult> AddStock(PartAddStockBindingModel partAddStockBinding)
        {
            if (ModelState.IsValid)
            {
                var result = await _partService.AddStock(partAddStockBinding.Name, partAddStockBinding.Quantity);

                if (result == false)
                {
                    this.ViewData["error"] = ControllerConstants.PartAddStockErrorMessage;
                    return this.Redirect($"/Part/Details?name={partAddStockBinding.Name}");
                }
                return this.Redirect($"/Part/Details?name={partAddStockBinding.Name}");
            }
            this.ViewData["error"] = ControllerConstants.InputErrorMessage;
            return this.Redirect($"/Part/Details?name={partAddStockBinding.Name}");
        }

        public async Task<IActionResult> Delete(string name)
        {
            await _partService.DeletePart(name);
            return RedirectToAction("All");
        }

        [HttpGet(Name = "Edit")]
        public async Task<IActionResult> Edit(string name)
        {
            return await Task.Run((() =>
                 this.View(_partService.GetPartByName(name).Result.To<PartEditViewModel>())));
        }

        [HttpPost(Name = "Edit")]
        public async Task<IActionResult> Edit(PartEditBindingModel partEditBindingModel)
        {
            if (ModelState.IsValid)
            {
                var result = await _partService.EditPart(partEditBindingModel.To<PartServiceModel>());

                if (result) return this.Redirect($"/Part/Details?name={partEditBindingModel.Name}");

                this.ViewData["error"] = ControllerConstants.PartEditErrorMessage;
                return this.RedirectToAction("Edit", partEditBindingModel);
            }

            this.ViewData["error"] = ControllerConstants.InputErrorMessage;
            return this.RedirectToAction("Edit", partEditBindingModel);
        }
    }
}

MDMS/Web/MDMS.Web/Controllers/PartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mdms.Data.Models;
using MDMS.GlobalConstants;
using MDMS.Services;
using MDMS.Services.Mapping;
using MDMS.Services.Models;
using MDMS.Web.BindingModels.Repair.Add;
using MDMS.Web.ViewModels.Part.All;
using MDMS.Web.ViewModels.Part.Details;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MDMS.Web.Controllers
{
    public class PartController : UserController
    {
        private readonly IPartService _partService;
        private readonly IRepairService _repairService;
        private readonly UserManager<MdmsUser> _userManager;

        public PartController(IPartService partService, IRepairService repairService, UserManager<MdmsUser> userManager)
        {
            _partService = partService;
            _repairService = repairService;
            _userManager = userManager;
        }

        [HttpGet(Name = "All")]
        public async Task<IActionResult> All([FromQuery]string criteria = null)
        {
            if (criteria == null) criteria = ServiceConstants.PartOrderName;

            var parts = await Task.Run(() => _partService.GetAllParts(criteria).To<PartAllViewModel>().ToList());

            this.ViewData["criteria"] = criteria.Replace("+", " ");
            if ((string)ViewData["criteria"] != ServiceConstants.PartOrderByPriceAscending &&
                (string)ViewData["criteria"] != ServiceConstants.PartOrderByPriceDescending &&
                (string)ViewData["criteria"] != ServiceConstants.PartOrderByStockAscending &&
                (string)ViewData["criteria"] != ServiceConstants.PartOrderByStockDescending &&
                (string)ViewData["criteria"] != ServiceConstants.PartOrderByUsedCountAscending &&
                (string)ViewData["criteria"] != ServiceConstants.PartOrderByUsedCountDescending)
            {
                this.ViewData["criteria"] = ServiceConstants.PartOrderName;
            }
            return this.View(parts);
        }

        [HttpGet(Name = "AddParts")]
        public async Task<IActionResult> AddParts([FromQuery]string criteria = null)
        {
            if (criteria == null) criteria = ServiceConstants.PartOrderName;

            var listOfParts = await _partService.GetAllParts(criteria).To<InternalRepairRepairPartBindingModel>().ToListAsync();
            var name = _repairService.GetActiveRepair(_userManager.GetUserId(User)).Result.Name;

            foreach (var part in listOfParts)
            {
                part.RepairName = name;
            }
            return View(listOfParts);
        }

        [HttpGet(Name = "Details")]
        public async Task<IActionResult> Details(string name)
        {
            var part = _partService.GetPartByName(name).Result.To<PartDetailsViewModel>();
            return View(await Task.Run((() => part)));
        }



        [HttpPost(Name = "AddParts")]
        public async Task<IActionResult> AddParts(List<InternalRepairRepairPartBindingModel> internalRepairAddPartsBindingModel)
        {
            if (!ModelState.IsValid)
            {
                this.ViewData["error"] = ControllerConstants.InputErrorMessage;
                return this.View(internalRepairAddPartsBindingModel);
            }
            if (!internalRepairAddPartsBindingModel.Any(x => x.Quantity > 0))
            {
                this.ViewData["error"] = ControllerConstants.PartsAddErrorMessage;
                return this.View(internalRepairAddPartsBindingModel);
            }

            var internalRepairId = _repairService.GetInternalRepairIdByName(internalRepairAddPartsBindingModel[0].RepairName).Result;
            var allPartsIds = _partService.GetAllParts(null).ToList();

            List<InternalRepairPartServiceModel> internalRepairPartServiceModels = new List<InternalRepairPartServiceModel>();

            foreach (var part in internalRepairAddPartsBindingModel.Where(x => x.Quantity > 0))
            {
                internalRepairPartServiceModels.Add(new InternalRepairPartServiceModel
                {
                    PartId = allPartsIds.SingleOrDefault(x => x.Name == part.Name)?.Id,
                    InternalRepairId = internalRepairId,
                    Quantity = part.Quantity
                });
            }

            await _repairService.AddPartsToInternalRepair(internalRepairPartServiceModels);

            return Redirect("/Repair/InternalActive");
        }
    }
}

MDMS/Web/MDMS.Web/ViewComponents/PartAllSortViewComponent.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MDMS.GlobalConstants;
using MDMS.Web.ViewModels.ViewComponents;
using Microsoft.AspNetCore.Mvc;

namespace MDMS.Web.ViewComponents
{
    public class PartAllSortViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<string> orderByList = new List<string>
            {
               ServiceConstants.PartOrderName,
               ServiceConstants.PartOrderByPriceAscending,
               ServiceConstants.PartOrderByPriceDescending,
               ServiceConstants.PartOrderByStockAscending,
               ServiceConstants.PartOrderByStockDescending,
               ServiceConstants.PartOrderByUsedCountAscending,
               ServiceConstants.PartOrderByUsedCountDescending,
            };
            var partAllSortViewComponentModels = await Task.Run((() => 
                orderByList
                .Select(vt => new PartAllSortViewComponentViewModel() {Name = vt})
                .ToList())); 

            return View(partAllSortViewComponentModels);
        }
    }
}

MDMS/Web/MDMS.Web/Views/Part/AddParts.cshtml
@model List<MDMS.Web.BindingModels.Repair.Add.InternalRepairRepairPartBindingModel>
@{
    ViewData["Title"] = "AddParts";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="d-flex justify-content-between">
    <div id="parts-search-bar-holder" class="form-group d-flex justify-content-between w-50">
        <input type="text" class="form-control text-primary" id="parts-search-bar" name="search" placeholder="Search..." />
    </div>
    <div id="sort-holder" class="form-group w-60 d-flex justify-content-center">
        <label for="sort" class="text-primary font-weight-bold w-30 h4 mt-1 text-bordered text-right">Order By: </label>
        <form id="order-form" action="/Part/AddParts" method="get">
            <select id="sort" class="form-control text-primary pl-2 ml-3 w-100" name="criteria">
                @if (this.ViewData["criteria"] != null)
                {
                    <option selected>@this.ViewData["criteria"]</option>
                }
                <vc:part-all-sort></vc:part-all-sort>
            </select>
        </form>
    </div>
</div>
<form method="post" class="form border-primary-4 rounded p-3 mx-auto w-85 mt-2 bg-white" enctype="multipart/form-data">
    @if (this.ViewData["error"] != null)
    {
        <ul>
            <li class="text-danger">@this.ViewData["error"]</li>
        </ul>
    }
    <div asp-validation-summary="All" class="text-danger"></div>
    <div id="products" class="mt-3">
        <table class="table table-sm table-hover bg-white">
            <thead>
            <tr class="row">
                <th scope="col" class="col-lg-1 text-primary text-center text-larger2">#</th>
                <th scope="col" class="col-lg-2 text-primary text-center text-larger2">Name</th>
                <th scope="col" class="col-lg-3 text-primary text-center text-larger2">Acquired From</th>
                <th scope="col" class="col-lg-1 text-primary text-center text-larger2">Used</th>
                <th scope="col" class="col-lg-2 text-primary text-center text-larger2">Stock</th>
                <th scope="col" class="col-lg-2 text-primary text-center text-larger2">Price</th>
                <th scope="col" class="col-lg-1 text-primary text-center text-larger2">Add</th>
            </tr>
            </thead>
            <tbody>
            @for (int i = 0; i < @Model.Count; i++)
            {
                <tr class="part row">
                    <td class="col-lg-1 text-primary text-center text-larger2">@(i + 1)</td>
                    <td class="col-lg-2 text-primary text-center text-larger2">
                        <input type="hidden" class="form-control text-primary text-center" id="name" asp-for="@Model[i].Name"/>@Model[i].Name
                    </td>
                    <td class="col-lg-3 text-primary text-center text-larger2">
                        <input type="hidden" class="form-control text-primary text-center" id="acquiredFromName" asp-for="@Model[i].AcquiredFromName"/>@Model[i].AcquiredFromName
                    </td>
                    <td class="col-lg-1 text-primary text-center text-larger2">
                        <input type="hidden" class="form-control text-primary text-center" id="usedCount" asp-for="@Model[i].UsedCount"/>@Model[i].UsedCount
                    </td>
                    <td class="col-lg-2 text-primary text-center text-larger2">
                        <input type="hidden" class="form-control text-primary text-center" id="stock" asp-for="@Model[i].Stock"/>@Model[i].Stock
                    </td>
                    <td class="col-lg-2 text-primary text-center text-larger2">
                        <input type="hidden" class="form-control text-primary text-center" id="price" asp-for="@Model[i].Price"/>@Model[i].Price
                    </td>
                    <td class="col-lg-1">
                        <input type="number" class="form-control text-primary text-center" id="addPartName" placeholder="0" asp-for="@Model[i].Quantity"/>
                        <input type="hidden" class="form-control text-primary text-center" id="repairName" asp-for="@Model[i].RepairName"/>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
    <hr class="hr-2 bg-primary">
    <div class="d-flex justify-content-center mt-3">
        <button class="btn btn-primary font-weight-bold">Add Selected Parts</button>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}


<script>
    $('#parts-search-bar').on("change paste keyup", function () {
        $('.part').show();

        let searchValue = $('#parts-search-bar').val();

        for (let elem of $('.part')) {
            let productName = $($(elem).children()[1]).text();

            if (!productName.toLowerCase().includes(searchValue.toLowerCase())) {
                $(elem).hide();
            }
        }
    });

      $('#sort').change(function () {
        $('#order-form').submit();
    });
</script>

MDMS/Web/MDMS.Web/Views/Part/All.cshtml
@model List<MDMS.Web.ViewModels.Part.All.PartAllViewModel>
@{
    ViewData["Title"] = "All";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="d-flex justify-content-between">
    <div id="part-search-bar-holder" class="form-group d-flex justify-content-between w-40">
        <input type="text" class="form-control text-primary" id="part-search-bar" name="search" placeholder="Search..." />
    </div>
    <div id="sort-holder" class="form-group w-60 d-flex justify-content-center">
        <label for="sort" class="text-primary font-weight-bold w-30 h4 mt-1 text-bordered text-right">Order By: </label>
        <form id="order-form" action="/Part/All" method="get">
            <select id="sort" class="form-control text-primary pl-2 ml-3 w-100" name="criteria">
                @if (this.ViewData["criteria"] != null)
                {
                <option selected>@this.ViewData["criteria"]</option>
                }
                <vc:part-all-sort></vc:part-all-sort>
            </select>
        </form>
    </div>
</div>
<hr class="hr-2 bg-primary">
<div id="parts" class="mt-3">
    @if (this.ViewData["error"] != null)
    {
        <ul>
            <li class="text-danger">@this.ViewData["error"]</li>
        </ul>
    }
    @if (@Model.Count == 0)
    {
        <h3 class="font-weight-bold text-bordered text-center"><ins>There are No Parts added yet.</ins></h3>

    }
    else
    {
        <table class="table table-sm table-hover bg-white">
            <thead>
            <tr class="row">
                <th scope="col" class="col-lg-1 text-primary text-center">#</th>
                <th scope="col" class="col-lg-2 text-primary text-center">Name</th>
                <th scope="col" class="col-lg-2 text-primary text-center">Acquired From</th>
                <th scope="col" class="col-lg-1 text-primary text-right">Price</th>
                <th scope="col" class="col-lg-1 text-primary text-right">Used</th>
                <th scope="col" class="col-lg-1 text-primary text-right">Used Sum</th>
                <th scope="col" class="col-lg-1 text-primary text-right">Stock</th>
                <th scope="col" class="col-lg-1 text-primary text-right">Stock Sum</th>
                <th scope="col" class="col-lg-2 text-primary text-center">Details</th>
            </tr>
            </thead>
            <tbody>
            @for (int i = 0; i < @Model.Count; i++)
            {

                <tr class="part row">
                    <td class="col-lg-1 text-primary text-center">@(i + 1)</td>
                    <td class="col-lg-2 text-primary text-center">@Model[i].Name</td>
                    <td class="col-lg-2 text-primary text-center">@Model[i].AcquiredFrom</td>
                    <td class="col-lg-1 text-primary text-right">@Model[i].Price</td>
                    <td class="col-lg-1 text-primary text-right">@Model[i].UsedCount</td>
                    <td class="col-lg-1 text-primary text-right">@(Model[i].UsedCount * Model[i].Price)</td>
                    <td class="col-lg-1 text-primary text-right">@Model[i].Stock</td>
                    <td class="col-lg-1 text-primary text-right">@(Model[i].Stock * Model[i].Price)</td>
                    <td class="col-lg-2 text-primary text-center">
                        <a href="/Part/Details?name=@Model[i].Name">Details</a>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    }
</div>

<script>
    $('#part-search-bar').on("change paste keyup", function () {
        $('.part').show();

        let searchValue = $('#part-search-bar').val();

        for (let elem of $('.part')) {
            let productName = $($(elem).children()[1]).text();

            if (!productName.toLowerCase().includes(searchValue.toLowerCase())) {
                $(elem).hide();
            }
        }
    });

    $('#sort').change(function () {
        $('#order-form').submit();
    });
</script>

MDMS/Web/MDMS.Web/Views/Part/Details.cshtml
@using MDMS.Web.ViewModels.Part.Details
@model PartDetailsViewModel
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    List<PartDetailsInternalRepairPartViewModel> repairs = Model.InternalRepairParts.OrderByDescending(x => x.Quantity).ToList();
}

<div class="d-flex justify-content-around row">
    <div id="internalActiveRepair-data-holder" class="w-30 rounded border-primary-4 bg-white">
        @if (this.ViewData["error"] != null)
        {
            <ul>
                <li class="text-danger">@this.ViewData["error"]</li>
            </ul>
        }
        <h3 class="text-center">Part</h3>
        <hr class="hr-2 bg-primary mt-2 w-50"/>
        <h4 class="text-center">Name: @Model.Name</h4>
        <h4 class="text-center">Acquired from: @Model.AcquiredFromName</h4>
        <hr class="hr-2 bg-primary mt-2 w-50"/>
        <h4 class="text-center">Price: $ @Model.Price </h4>
        <hr class="hr-2 bg-primary mt-2 w-50"/>
        <h4 class="text-center">Stock: @Model.Stock </h4>
        <h4 class="text-center">Stock Value: $ @(Model.Stock * Model.Price)</h4>
        <hr class="hr-2 bg-primary mt-2 w-50"/>
        <h4 class="text-center">Used in Repairs: @Model.UsedCount </h4>
        <h4 class="text-center">Used in Repairs Value: $ @(Model.UsedCount * Model.Price)</h4>
        <hr class="hr-2 bg-primary mt-0 w-50"/>
        @if (User.IsInRole("Admin"))
        {
            <div id="navigation-holder" class="mt-4 d-flex justify-content-around">
                <a href="/Administration/Part/Edit/@Model.Name" class="btn btn-primary text-white font-weight-bold">Edit</a>
                <button class="btn btn-primary text-white font-weight-bold" data-toggle="modal" data-target="#orderModal">Add Stock</button>
                <button class="btn btn-primary text-white font-weight-bold" data-toggle="modal" data-target="#vehicleModal">Delete</button>
            </div>
            <hr class="hr-2 bg-primary mt-3 w-50"/>
        }
    </div>

    <div id="internalActiveRepairParts-data-holder" class="w-60 rounded border-primary-4 bg-white">
        <h4 class="text-center mt-2">@Model.Name are used in these Repairs</h4>
        <hr class="hr-2 bg-primary mt-2 w-50" />
        <div id="repairs" class="mt-3">
            @if (@Model.InternalRepairParts.Count <= 0)
            {
                <h3 class="text-center">@Model.Name are Not Used in any repairs yet.</h3>
            }
            else
            {
                <table class="table table-sm table-hover bg-white">
                    <thead>
                        <tr class="row">
                            <th scope="col" class="col-md-1 text-primary text-center">#</th>
                            <th scope="col" class="col-md-6 text-primary text-center">Name</th>
                            <th scope="col" class="col-md-1 text-primary text-right">Count</th>
                            <th scope="col" class="col-md-1 text-primary text-right">Parts Cost</th>
                            <th scope="col" class="col-md-1 text-primary text-right">Rep Cost</th>
                            <th scope="col" class="col-md-1 text-primary text-center">Finished</th>
                            <th scope="col" class="col-md-1 text-primary text-center">Details</th>
                        </tr>
                    </thead>
                    <tbody>

                        @for (int i = 0; i < repairs.Count; i++)
                        {

                            <tr class="row">
                                <td class="col-md-1 text-primary text-center">@(i + 1)</td>
                                <td class="col-md-6 text-primary text-center">@repairs[i].InternalRepairName</td>
                                <td class="col-md-1 text-primary text-right">@repairs[i].Quantity</td>
                                <td class="col-md-1 text-primary text-right">$ @repairs[i].InternalRepairParsCost</td>
                                <td class="col-md-1 text-primary text-right">$ @repairs[i].InternalRepairRepairCost</td>
                                
                                @if (@repairs[i].InternalRepairFinishedOn == null)
                                {
                                    <td class="col-md-1 text-primary text-center">Active</td>
                                }
                                else
                                {
                                    <td class="col-md-1 text-primary text-center">@repairs[i].InternalRepairFinishedOn?.ToString("d")</td>
                                }
                                <td class="col-lg-1 text-primary text-center">
                                    <a href="/Repair/InternalDetails?name=@repairs[i].InternalRepairName.Replace(" ","_")">Details</a>
                                </td>
                            </tr>

                        }
                    </tbody>
                </table>
            }
        </div>
    </div>
</div>

<div class="modal fade" id="orderModal" tabindex="-1" role="dialog" aria-labelledby="orderModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="partsAddModalLabel">Add Parts - @Model.Name</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="addParts-form" action="/Administration/Part/AddStock" method="post">
                    <div class="form-group">
                        <div class="d-flex justify-content-center">
                            <label asp-for="Quantity" class="h4">Add Stock of @Model.Name</label>
                        </div>
                        <input type="number"
                               class="form-control"
                               id="quantity"
                               name="Quantity"
                               asp-for="Quantity">
                        <input type="hidden" value="@Model.Name" name="Name" />
                    </div>
                    <div class="d-flex justify-content-center mt-1">
                        <span asp-validation-for="Quantity" class="text-danger"></span>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="add-parts-button">Add</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="vehicleModal" tabindex="-1" role="dialog" aria-labelledby="orderModalLabel1" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="partDeleteModalLabel">Part - @Model.Name</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5 class="text-danger text-center">Part will be DELETED PERMANENTLY</h5>
                <h5 class="text-danger text-center">Do you with to proceed ?</h5>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                <a href="/Administration/Part/Delete?name=@Model.Name" class="btn btn-primary font-weight-bold" id="deletePart">DELETE Part</a>
            </div>
        </div>
    </div>
</div>

<script>
    $('#add-parts-button').click(function () {
        $('#addParts-form').submit();
    });
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}