MDMS/Web/MDMS.Web/Areas/Administration/Controllers/RepairController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Mdms.Data.Models;
using MDMS.GlobalConstants;
using MDMS.Services;
using MDMS.Services.Mapping;
using MDMS.Services.Models;
using MDMS.Web.BindingModels.Repair.Create;
using MDMS.Web.BindingModels.Repair.Finish;
using MDMS.Web.ViewModels.Repair.Finish;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace MDMS.Web.Areas.Administration.Controllers
{
    public class RepairController : AdminController
    {
        private readonly IRepairService _repairService;
        private readonly IVehicleService _vehicleService;
        private readonly UserManager<MdmsUser> _userManager;

        public RepairController(IRepairService repairService, IVehicleService vehicleService, UserManager<MdmsUser> userManager)
        {
            _repairService = repairService;
            _vehicleService = vehicleService;
            _userManager = userManager;
        }
        [HttpGet]
        [Route("/Administration/Repair/Provider/Create")]
        public async Task<IActionResult> CreateProvider() => await Task.Run(() => this.View("Provider/Create"));


        [HttpPost]
        [Route("/Administration/Repair/Provider/Create")]
        public async Task<IActionResult> CreateProvider(ExternalRepairProviderCreateBindingModel externalRepairProviderBindingModel)
        {
            if (ModelState.IsValid)
            {
                var vehicleProviderServiceModel = AutoMapper.Mapper.Map<ExternalRepairProviderServiceModel>(externalRepairProviderBindingModel);

                var result = await _repairService.CreateExternalRepairProvider(vehicleProviderServiceModel);

                if (result) return this.Redirect("/");

                this.ViewData["error"] = ControllerConstants.RepairProviderCreateErrorMessage;
                return this.View("Provider/Create", externalRepairProviderBindingModel);
            }
            this.ViewData["error"] = ControllerConstants.InputErrorMessage;
            return this.View("Provider/Create", externalRepairProviderBindingModel);
        }

        [HttpGet(Name = "CreateExternal")]
        public async Task<IActionResult> CreateExternal(string name)
        {
            return await Task.Run(() =>
                    this.View(_vehicleService.GetVehicleByName(name).Result.To<ExternalRepairCreateBindingModel>()));
        }


        [HttpPost(Name = "CreateExternal")]
        public async Task<IActionResult> CreateExternal(ExternalRepairCreateBindingModel externalRepairCreateBindingModel)
        {
            if (ModelState.IsValid)
            {
                var externalRepairServiceModel = externalRepairCreateBindingModel.To<ExternalRepairServiceModel>();
                externalRepairServiceModel.MdmsUserId = _userManager.GetUserId(User);
                externalRepairServiceModel.RepairedSystem = new RepairedSystemServiceModel { Name = externalRepairCreateBindingModel.RepairedSystemName };
                externalRepairServiceModel.ExternalRepairProvider = new ExternalRepairProviderServiceModel { Name = externalRepairCreateBindingModel.ExternalRepairProviderName };
                externalRepairServiceModel.Name = "External_" +
                                                  externalRepairCreateBindingModel.RepairedSystemName + "_" +
                                                  externalRepairCreateBindingModel.Make + "_" +
                                                  externalRepairCreateBindingModel.Model + "_" +
                                                  externalRepairCreateBindingModel.VSN;
                var result = await _repairService.CreateExternal(externalRepairServiceModel);

                if (result) return this.Redirect("/");

                this.ViewData["error"] = ControllerConstants.RepairCreateErrorMessage;
                return this.View(externalRepairCreateBindingModel);
            }
            this.ViewData["error"] = ControllerConstants.InputErrorMessage;
            return this.View(externalRepairCreateBindingModel);
        }

        [HttpGet(Name = "ExternalActive")]
        public async Task<IActionResult> ExternalActive() => await Task.Run((() => this.View(
            AutoMapper.Mapper.Map<List<ExternalRepairActiveViewModel>>(_repairService.GetActiveRepairs(_userManager.GetUserId(User))))));

        [HttpGet(Name = "ExternalActiveFinish")]
        public async Task<IActionResult> ExternalActiveFinish(string name)
        {
            var repair = await _repairService.GetExternalActiveRepair(name);
                var viewRepair = AutoMapper.Mapper.Map<ExternalRepairFinishBindingModel>(repair);
                return this.View(viewRepair);
            }

        [HttpPost(Name = "ExternalActiveFinish")]
        public async Task<IActionResult> ExternalActiveFinish(ExternalRepairFinishBindingModel externalRepairFinishBindingModel)
        {

            if (!ModelState.IsValid)
            {
                this.ViewData["error"] = ControllerConstants.InputErrorMessage;
                return this.View(externalRepairFinishBindingModel);
            }

            var result = await _repairService.FinalizeExternal(externalRepairFinishBindingModel.To<ExternalRepairServiceModel>());
            if (result) return this.Redirect("/");

            this.ViewData["error"] = ControllerConstants.RepairFinalizeErrorMessage;
            return this.View(externalRepairFinishBindingModel);
        }
    }
}

MDMS/Web/MDMS.Web/Controllers/RepairController.cs
using System;
using System.Threading.Tasks;
using Mdms.Data.Models;
using MDMS.GlobalConstants;
using MDMS.Services;
using MDMS.Services.Mapping;
using MDMS.Services.Models;
using MDMS.Web.BindingModels.Repair.Active;
using MDMS.Web.BindingModels.Repair.Create;
using MDMS.Web.ViewModels.Repair.All;
using MDMS.Web.ViewModels.Repair.Details;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MDMS.Web.Controllers
{
    public class RepairController : UserController
    {
        private readonly IVehicleService _vehicleService;
        private readonly IRepairService _repairService;
        private readonly UserManager<MdmsUser> _userManager;

        public RepairController(IVehicleService vehicleService, IRepairService repairService, UserManager<MdmsUser> userManager)
        {
            _vehicleService = vehicleService;
            _repairService = repairService;
            _userManager = userManager;
        }

        [HttpGet(Name = "CreateInternal")]
        public async Task<IActionResult> CreateInternal(string name)
        {
            return await Task.Run(() =>
                    this.View(_vehicleService.GetVehicleByName(name).Result.To<InternalRepairCreateBindingModel>()));
        }


        [HttpPost(Name = "CreateInternal")]
        public async Task<IActionResult> CreateInternal(InternalRepairCreateBindingModel internalRepairCreateBindingModel)
        {
            if (ModelState.IsValid)
            {
                var internalRepairServiceModel = internalRepairCreateBindingModel.To<InternalRepairServiceModel>();
                internalRepairServiceModel.MdmsUserId = _userManager.GetUserId(User);
                internalRepairServiceModel.RepairedSystem = new RepairedSystemServiceModel { Name = internalRepairCreateBindingModel.RepairedSystemName };
                internalRepairServiceModel.Name = "Internal_" +
                                                  internalRepairCreateBindingModel.RepairedSystemName + "_" +
                                                  internalRepairCreateBindingModel.Make + "_" +
                                                  internalRepairCreateBindingModel.Model + "_" +
                                                  internalRepairCreateBindingModel.VSN;
                var result = await _repairService.CreateInternal(internalRepairServiceModel);

                if (result) return this.Redirect("/");

                this.ViewData["error"] = ControllerConstants.RepairCreateErrorMessage;
                return this.View(internalRepairCreateBindingModel);
            }
            this.ViewData["error"] = ControllerConstants.InputErrorMessage;
            return this.View(internalRepairCreateBindingModel);
        }

        [HttpGet(Name = "InternalActive")]
        public async Task<IActionResult> InternalActive() => this.View(
            AutoMapper.Mapper.Map<InternalRepairActiveBindingModel>(await _repairService.GetActiveRepair(_userManager.GetUserId(User))));

        [HttpPost(Name = "InternalActiveFinish")]
        public async Task<IActionResult> InternalActiveFinish(InternalRepairActiveBindingModel internalRepairActiveBindingModel)
        {
            if (!ModelState.IsValid)
            {
                this.ViewData["error"] = ControllerConstants.InputErrorMessage;
                return RedirectToAction("InternalActive");
            }
            var result = await _repairService.FinalizeInternal(internalRepairActiveBindingModel.Id, internalRepairActiveBindingModel.HoursWorked);
            if (!result)
            {
                this.ViewData["error"] = ControllerConstants.RepairFinalizeErrorMessage;
                return RedirectToAction("InternalActive");
            }
            return Redirect("/");
        }


        [HttpGet(Name = "All")]
        public async Task<IActionResult> All() => View(new RepairsAllViewModel
        {
            ExternalRepairAllViewModels = await _repairService.GetAllExternalRepairs().To<ExternalRepairAllViewModel>().ToListAsync(),
            InternalRepairAllViewModels = await _repairService.GetAllInternalRepairs().To<InternalRepairAllViewModel>().ToListAsync()
        });

        [HttpGet(Name = "InternalDetails")]
        public async Task<IActionResult> InternalDetails(string name)
        {
            return await Task.Run((() =>
                    View(_repairService.GetInternalRepairByName(name.Replace(" ", "_")).Result.To<InternalRepairDetailsViewModel>())));
        }


        [HttpGet(Name = "ExternalDetails")]
        public async Task<IActionResult> ExternalDetails(string name)
        {

            return await Task.Run((() =>
                View(_repairService.GetExternalRepairByName(name.Replace(" ", "_")).Result.To<ExternalRepairDetailsViewModel>())));
        }
    }
}

MDMS/Web/MDMS.Web/ViewComponents/RepairedSystemViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MDMS.Services;
using MDMS.Web.ViewModels.ViewComponents;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MDMS.Web.ViewComponents
{
    public class RepairedSystemViewComponent : ViewComponent
    {
        private readonly IRepairService _repairService;

        public RepairedSystemViewComponent(IRepairService repairService)
        {
            _repairService = repairService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var repairedSystemViewComponentViewModels = await _repairService.GetAllRepairedSystems()
                .OrderBy(vt => vt.Name)
                .Select(vt => new RepairedSystemViewComponentViewModel() { Name = vt.Name })
                .ToListAsync();

            return View(repairedSystemViewComponentViewModels);
        }
    }
}

MDMS/Web/MDMS.Web/Views/Repair/All.cshtml
@model MDMS.Web.ViewModels.Repair.All.RepairsAllViewModel
@{
    ViewData["Title"] = "All";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="d-flex justify-content-center">
    <h3 style="font-size: 30px" class="font-weight-bold text-bordered"><ins>You can search by anything in NAME column :</ins></h3>
    <div id="repair-search-bar-holder" class="form-group d-flex justify-content-between w-50">
        <input type="text" class="form-control text-primary" id="repair-search-bar" name="search" placeholder="Search..."/>
    </div>
</div>
<hr class="hr-2 bg-primary">
<div id="products" class="mt-3">
    @if (@Model.ExternalRepairAllViewModels.Count + Model.InternalRepairAllViewModels.Count == 0)
    {
        <h3 class="font-weight-bold text-bordered text-center"><ins>There are No Repairs added yet.</ins></h3>
    }
    else
    {
        <table class="table table-sm table-hover bg-white">
            <thead>
                <tr class="row">
                    <th scope="col" class="col-lg-1 text-primary text-center">#</th>
                    <th scope="col" class="col-lg-4 text-primary text-center"><ins>NAME (Type RepairedSystem (Vehicle: Make Model VSN) Stated)</ins></th>
                    <th scope="col" class="col-lg-1 text-primary text-right">Cost</th>
                    <th scope="col" class="col-lg-1 text-primary text-center">Mechanic</th>
                    <th scope="col" class="col-lg-2 text-primary text-center">Started On</th>
                    <th scope="col" class="col-lg-2 text-primary text-center">Finished On</th>
                    <th scope="col" class="col-lg-1 text-primary text-center">Details</th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < @Model.InternalRepairAllViewModels.Count; i++)
                {

                    <tr class="repair row">
                        <td class="col-lg-1 text-primary text-center">@(i + 1)</td>
                        <td class="col-lg-4 text-primary text-center">@Model.InternalRepairAllViewModels[i].Name</td>
                        <td class="col-lg-1 text-primary  text-right">@Model.InternalRepairAllViewModels[i].RepairCost</td>
                        <td class="col-lg-1 text-primary text-center">@Model.InternalRepairAllViewModels[i].MdmsUserUserName</td>
                        <td class="col-lg-2 text-primary text-center">@Model.InternalRepairAllViewModels[i].StartedOn.ToString("f")</td>
                        @if (@Model.InternalRepairAllViewModels[i].FinishedOn == null)
                        {
                            <td class="col-lg-2 text-primary text-center">This repair has not been finished yet.</td>
                        }
                        else
                        {
                            <td class="col-lg-2 text-primary text-center">@Model.InternalRepairAllViewModels[i].FinishedOn?.ToString("f")</td>
                        }
                        <td class="col-lg-1 text-center">
                            <a href="/Repair/InternalDetails?name=@Model.InternalRepairAllViewModels[i].Name.Replace(" ", "_")">Details</a>
                        </td>
                    </tr>
                }
                @for (int i = @Model.InternalRepairAllViewModels.Count; i < @Model.ExternalRepairAllViewModels.Count + @Model.InternalRepairAllViewModels.Count; i++)
                {

                    <tr class="repair row">
                        <td class="col-lg-1 text-primary text-center">@(i + 1)</td>
                        <td class="col-lg-4 text-primary text-center">@Model.ExternalRepairAllViewModels[i - @Model.InternalRepairAllViewModels.Count].Name</td>
                        <td class="col-lg-1 text-primary  text-right">@Model.ExternalRepairAllViewModels[i - @Model.InternalRepairAllViewModels.Count].RepairCost</td>
                        <td class="col-lg-1 text-primary text-center">@Model.ExternalRepairAllViewModels[i - @Model.InternalRepairAllViewModels.Count].MdmsUserUserName</td>
                        <td class="col-lg-2 text-primary text-center">@Model.ExternalRepairAllViewModels[i - @Model.InternalRepairAllViewModels.Count].StartedOn.ToString("f")</td>
                        @if (@Model.ExternalRepairAllViewModels[i - @Model.InternalRepairAllViewModels.Count].FinishedOn == null)
                        {
                            <td class="col-lg-2 text-primary text-center">This repair has not been finished yet.</td>
                        }
                        else
                        {
                            <td class="col-lg-2 text-primary text-center">@Model.ExternalRepairAllViewModels[i - @Model.InternalRepairAllViewModels.Count].FinishedOn?.ToString("f")</td>
                        }
                        <td class="col-lg-1 text-center">
                            <a href="/Repair/ExternalDetails?name=@Model.ExternalRepairAllViewModels[i - @Model.InternalRepairAllViewModels.Count].Name.Replace(" ", "_")">Details</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>

<script>
    $('#repair-search-bar').on("change paste keyup", function () {
        $('.repair').show();

        let searchValue = $('#repair-search-bar').val();

        for (let elem of $('.repair')) {
            let productName = $($(elem).children()[1]).text();

            if (!productName.toLowerCase().includes(searchValue.toLowerCase())) {
                $(elem).hide();
            }
        }
    });
</script>

MDMS/Web/MDMS.Web/Views/Repair/CreateInternal.cshtml
@model MDMS.Web.BindingModels.Repair.InternalRepairCreateBindingModel
@{
    ViewData["Title"] = "CreateInternal";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="bg-primary text-white font-weight-bold text-center p-3 w-45 mx-auto rounded">Initialize Internal Repair</h1>
<h2 class="bg-primary text-white text-center p-3 w-45 mx-auto rounded">@Model.Make @Model.Model @Model.VSN</h2>
<form method="post" action="/Repair/CreateInternal" class="form border-primary-4 rounded p-3 w-45 mx-auto mt-3 bg-white">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    @if (this.ViewData["error"] != null)
    {
        <ul>
            <li class="text-danger">@this.ViewData["error"]</li>
        </ul>
    }
    <div class="form-group mx-auto">
        <div class="d-flex justify-content-center">
            <label asp-for="Description" class="text-primary h5">Description</label>
        </div>
        <textarea type="text" class="form-control" id="description" rows="5" placeholder="Description..."
                  asp-for="Description"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group mx-auto">
        <div class="d-flex justify-content-center">
            <label asp-for="RepairedSystem" class="text-primary h5">Repaired System</label>
        </div>
        <select class="form-control text-primary text-center" id="partsProvider" asp-for="RepairedSystem">
            <option selected disabled>--- Select Part Provider ---</option>
            <vc:repaired-system></vc:repaired-system>
        </select>
        <span asp-validation-for="RepairedSystem" class="text-danger"></span>
    </div>
    <div class="form-group mx-auto">
        <div class="d-flex justify-content-center">
            <label asp-for="Mileage" class="text-primary h5">Mileage</label>
        </div>
        <input type="number"
               step="1"
               class="form-control text-primary text-center"
               id="mileage"
               placeholder="Mileage..."
               asp-for="Mileage">
        <span asp-validation-for="Mileage" class="text-danger"></span>
    </div>
    <hr class="hr-2 bg-primary mt-4">
    <div class="d-flex justify-content-center mt-3">
        <button class="btn btn-primary font-weight-bold">Initialize Internal Repair</button>
    </div>

</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MDMS/Web/MDMS.Web/Views/Repair/ExternalDetails.cshtml
@model MDMS.Web.ViewModels.Repair.Details.ExternalRepairDetailsViewModel
@{
    ViewData["Title"] = "ExternalDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="d-flex justify-content-around row">
    <div id="internalActiveRepair-data-holder" class="w-45 rounded border-primary-4 bg-white">
        <hr class="hr-2 bg-primary mt-2 w-50" />
        <h4 class="text-center">Internal Repair</h4>
        <hr class="hr-2 bg-primary mt-2 w-50" />
        @if (@Model.VehicleIsDeleted)
        {
            <h4 class="text-center">Vehicle: @Model.VehicleMake @Model.VehicleModel</h4>
            <h4 class="text-center">VSN: @Model.VehicleVSN</h4>
            <h4 class="text-center">Mileage: @Model.Mileage</h4>
        }
        else
        {
            <a href="/Vehicle/Details/@Model.VehicleName">
                <h4 class="text-center">Vehicle: @Model.VehicleMake @Model.VehicleModel</h4>
                <h4 class="text-center">VSN: @Model.VehicleVSN</h4>
                <h4 class="text-center">Mileage: @Model.Mileage</h4>
            </a>
        }
        <hr class="hr-2 bg-primary mt-2 w-50" />
        <h4 class="text-center">Mechanic: @Model.MdmsUserUsername</h4>
        <h4 class="text-center">Started on: @Model.StartedOn.ToString("d")</h4>
        @if (@Model.FinishedOn == null)
        {
            <h4 class="text-center">Finished on: Repair is Not finished yet.</h4>
        }
        else
        {
            <h4 class="text-center">Finished on: @Model.FinishedOn?.ToString("d")</h4>

        }
        <h4 class="text-center">Repaired System: @Model.RepairedSystemName</h4>
        <hr class="hr-2 bg-primary mt-2 w-50" />
        <h4 class="text-center">Description:</h4>
        <p class="w-75 text-center text-dark text-larger2 m-auto">@Model.Description</p>
        <hr class="hr-2 bg-primary mt-2 w-50" />
        <h4 class="text-center">Repair Provider: @Model.ExternalRepairProviderName </h4>
        <hr class="hr-2 bg-primary mt-2 w-50" />
        <h4 class="text-center">Labor Cost: $ @Model.LaborCost </h4>
        <h4 class="text-center">Parts Cost: $ @Model.PartsCost</h4>
        <h4 class="text-center">Repair Cost: $ @Model.RepairCost</h4>
        <hr class="hr-2 bg-primary mt-0 w-50" />
    </div>
</div>

MDMS/Web/MDMS.Web/Views/Repair/InternalActive.cshtml
@model MDMS.Web.BindingModels.Repair.Active.InternalRepairActiveBindingModel
@{
    ViewData["Title"] = "InternalActive";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="d-flex justify-content-around row">
    @if (@Model.Name == null)
    {
        <h3 class="font-weight-bold text-bordered text-center"><ins>You have NO Active Repairs</ins></h3>

    }
    else
    {
        <div id="internalActiveRepair-data-holder" class="w-45 rounded border-primary-4 bg-white">
            <div asp-validation-summary="All" class="text-danger"></div>
            @if (this.ViewData["error"] != null)
            {
                <ul>
                    <li class="text-danger">@this.ViewData["error"]</li>
                </ul>
            }
            <h3 class="text-center">Internal Repair</h3>
            <hr class="hr-2 bg-primary mt-2 w-50" />
            <a href="/Vehicle/Details/@Model.VehicleName">
                <h4 class="text-center">Vehicle: @Model.VehicleMake @Model.VehicleModel</h4>
                <h4 class="text-center">VSN: @Model.VehicleVSN</h4>
                <h4 class="text-center">Mileage: @Model.Mileage</h4>
            </a>
            <hr class="hr-2 bg-primary mt-2 w-50" />
            <h4 class="text-center">Mechanic: @Model.MdmsUserUsername Started on: @Model.StartedOn.ToString("d")</h4>
            <h4 class="text-center">Repairing: @Model.RepairedSystemName</h4>
            <hr class="hr-2 bg-primary mt-2 w-50" />
            <div class="form-group mx-auto">
                <div class="d-flex justify-content-center">
                    <label asp-for="Description" class="h4">Description</label>
                </div>
                <textarea type="text" class="form-control w-75 border-primary-2 m-auto" id="descriptionExternal" name="Description" rows="5"
                          placeholder="You Must have a least one symbol in Description"
                          asp-for="Description"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="d-flex justify-content-center mt-1">
                <button class="btn btn-primary font-weight-bold" onclick="internalEdit()">Edit Description</button>
            </div>
            <hr class="hr-2 bg-primary mt-2 w-50" />
            <h3 class="text-center">Parts Cost: $@Model.RepairCost</h3>
            <div class="d-flex justify-content-center mt-1">
                <a href="/Part/AddParts?name=@Model.Name" class="btn btn-primary text-white font-weight-bold mb-3">Add Parts</a>
            </div>
            <hr class="hr-2 bg-primary mt-0 w-50" />

            <form method="post" action="/Repair/InternalActiveFinish" class="form-group mx-auto">
                <div class="d-flex justify-content-center">
                    <label asp-for="HoursWorked" class="h4">Hours Worked</label>
                </div>
                <div class="d-flex justify-content-center">
                    <input type="number"
                           step="0.01"
                           class="form-control w-50 justify-content-center text-primary text-center"
                           id="HoursWorked"
                           name="HoursWorked"
                           placeholder="HoursWorked..."
                           asp-for="HoursWorked">
                </div>
                <div class="d-flex justify-content-center mt-1">
                    <span asp-validation-for="HoursWorked" class="text-danger"></span>
                </div>
                <div class="d-flex justify-content-center mt-1">
                    <button class="btn btn-primary font-weight-bold">Finalize Repair</button>
                </div>

                <input type="hidden" value="@Model.Id" name="id" id="id" />

            </form>
        </div>


        <div id="internalActiveRepairParts-data-holder" class="w-45 rounded border-primary-4 bg-white">
            <h3 class="text-center mt-2">Parts</h3>
            <hr class="hr-2 bg-primary mt-2 w-50" />
            <div id="repairs" class="mt-3">
                @if (@Model.InternalRepairParts.Count <= 0)
                {
                    <h3 class="text-center">There are No Repairs yet.</h3>
                }
                else
                {
                    <table class="table table-sm table-hover bg-white">
                        <thead>
                            <tr class="row">
                                <th scope="col" class="col-md-1 text-primary text-center">#</th>
                                <th scope="col" class="col-md-3 text-primary text-center">Name</th>
                                <th scope="col" class="col-md-3 text-primary text-center">Provider</th>
                                <th scope="col" class="col-md-2 text-primary text-center">Price</th>
                                <th scope="col" class="col-md-1 text-primary text-center">Quantity</th>
                                <th scope="col" class="col-md-2 text-primary text-center">Sum</th>

                            </tr>
                        </thead>
                        <tbody>

                            @for (int i = 0; i < @Model.InternalRepairParts.Count; i++)
                            {
                                <tr class="row">
                                    <td class="col-md-1 text-primary text-center">@(i + 1)</td>
                                    <td class="col-md-3 text-primary text-center">@Model.InternalRepairParts[i].PartName</td>
                                    <td class="col-md-3 text-primary text-center">@Model.InternalRepairParts[i].PartAcquiredFromName</td>
                                    <td class="col-md-2 text-primary text-center">$ @Model.InternalRepairParts[i].PartPrice</td>
                                    <td class="col-md-1 text-primary text-center">@Model.InternalRepairParts[i].Quantity</td>
                                    <td class="col-md-2 text-primary text-center">$ @(Model.InternalRepairParts[i].Quantity * Model.InternalRepairParts[i].PartPrice)</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
            </div>
        </div>
    }
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}